"""init schema

Revision ID: 1f11b7ada8fd
Revises: 
Create Date: 2026-03-06 10:51:29.175272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f11b7ada8fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )

    op.bulk_insert(
        sa.table('roles',
                 sa.column('id', sa.Integer()),
                 sa.column('name', sa.String()),
                 sa.column('description', sa.String())),
        [
            {'id': 1, 'name': 'user', 'description': 'Regular user'},
            {'id': 2, 'name': 'manager', 'description': 'Manager user'},
            {'id': 3, 'name': 'admin', 'description': 'Admin user'},
        ]
    )

    op.bulk_insert(
        sa.table('permissions',
                 sa.column('id', sa.Integer()),
                 sa.column('code', sa.String()),
                 sa.column('description', sa.String())),
        [
            {'id': 1, 'code': 'user.create', 'description': 'Создание пользователей'},
            {'id': 2, 'code': 'user.read', 'description': 'Просмотр пользователей'},
            {'id': 3, 'code': 'user.update', 'description': 'Редактирование пользователей'},
            {'id': 4, 'code': 'user.delete', 'description': 'Удаление пользователей'},
            {'id': 5, 'code': 'role.create', 'description': 'Создание ролей'},
            {'id': 6, 'code': 'role.read', 'description': 'Просмотр ролей'},
            {'id': 7, 'code': 'role.update', 'description': 'Редактирование ролей'},
            {'id': 8, 'code': 'role.delete', 'description': 'Удаление ролей'},
            {'id': 9, 'code': 'role.assign_permission', 'description': 'Назначение разрешений ролям'},
            {'id': 10, 'code': 'permission.create', 'description': 'Создание разрешений'},
            {'id': 11, 'code': 'permission.read', 'description': 'Просмотр разрешений'},
            {'id': 12, 'code': 'permission.update', 'description': 'Редактирование разрешений'},
            {'id': 13, 'code': 'permission.delete', 'description': 'Удаление разрешений'},
        ]
    )

    op.bulk_insert(
        sa.table('roles_permissions',
                 sa.column('role_id', sa.Integer()),
                 sa.column('permission_id', sa.Integer())),
        [
            # === Admin ===
            {'role_id': 3, 'permission_id': 1},
            {'role_id': 3, 'permission_id': 2},
            {'role_id': 3, 'permission_id': 3},
            {'role_id': 3, 'permission_id': 4},
            {'role_id': 3, 'permission_id': 5},
            {'role_id': 3, 'permission_id': 6},
            {'role_id': 3, 'permission_id': 7},
            {'role_id': 3, 'permission_id': 8},
            {'role_id': 3, 'permission_id': 9},
            {'role_id': 3, 'permission_id': 10},
            {'role_id': 3, 'permission_id': 11},
            {'role_id': 3, 'permission_id': 12},
            {'role_id': 3, 'permission_id': 13},

            # === Manager ===
            {'role_id': 2, 'permission_id': 2},  # user.read

            # === User — ТОЛЬКО СВОЙ ПРОФИЛЬ ===
            {'role_id': 1, 'permission_id': 2},  # user.read
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles_permissions')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
