services:
  auth:
    build: ./auth_service
    image: marketplace_auth
    container_name: auth
    restart: always
    command: 'sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --no-access-log"'
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres_auth:
        condition: service_healthy
      redis_auth:
        condition: service_started
    networks:
      - backend_network
    volumes:
      - ./auth_service:/auth_service

  postgres_auth:
    image: postgres:16-alpine
    container_name: postgres_auth
    restart: always
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - backend_network

  redis_auth:
    image: redis:7-alpine
    container_name: redis_auth
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 64mb
      --maxmemory-policy allkeys-lru
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 16mb
    volumes:
      - redis_data_auth:/data
    networks:
      - backend_network

  prometheus_auth:
    image: prom/prometheus:v3.11.3
    container_name: prometheus_auth
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./auth_service/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - backend_network
    depends_on:
      - auth

  grafana_auth:
    image: grafana/grafana:13.0.1
    container_name: grafana_auth
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./auth_service/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./auth_service/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./auth_service/grafana/dashboards:/etc/grafana/dashboards:ro
    networks:
      - backend_network
    depends_on:
      - prometheus_auth

  node_exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - backend_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - backend_network

  logstash:
    image: docker.elastic.co/logstash/logstash:9.4.0
    container_name: logstash
    restart: unless-stopped
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m -Djava.net.preferIPv4Stack=true"
    volumes:
      - ./auth_service/elk-stack/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "9600:9600"
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    networks:
      - backend_network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.0
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - backend_network
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -f http://localhost:5601/api/status" ]
      interval: 5s
      timeout: 5s
      retries: 15

  kibana-init:
    image: curlimages/curl:8.20.0
    container_name: kibana-init
    restart: no
    depends_on:
      kibana:
        condition: service_healthy
    volumes:
      - ./auth_service/elk-stack/kibana/init.sh:/init.sh:ro
      - ./auth_service/elk-stack/kibana/auth_dashboard.ndjson:/usr/share/kibana/data/auth_dashboard.ndjson:ro
    command: ["/bin/sh", "/init.sh"]
    networks:
      - backend_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.4.0
    container_name: filebeat
    restart: unless-stopped
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - ./auth_service/elk-stack/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
    networks:
      - backend_network


volumes:
  postgres_data_auth:
  redis_data_auth:
  prometheus_data:
  grafana_data:
  elastic_data:

networks:
  backend_network:
    driver: bridge