services:
  auth:
    build: ./auth_service
    image: marketplace_auth
    container_name: auth
    restart: always
    # применяем миграции и запускаем сервер
    command: 'sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"'
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres_auth:
        condition: service_healthy
      redis_auth:
        condition: service_started
    networks:
      - backend_network
    volumes:
      - ./auth_service:/auth_service

  postgres_auth:
    image: postgres:16-alpine
    container_name: postgres_auth
    restart: always
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - backend_network

  redis_auth:
    image: redis:7-alpine
    container_name: redis_auth
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 64mb
      --maxmemory-policy allkeys-lru
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 16mb
    volumes:
      - redis_data_auth:/data
    networks:
      - backend_network

  prometheus_auth:
    image: prom/prometheus:v3.11.3
    container_name: prometheus_auth
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./auth_service/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - backend_network
    depends_on:
      - auth

  grafana_auth:
    image: grafana/grafana:13.0.1
    container_name: grafana_auth
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./auth_service/grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./auth_service/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./auth_service/grafana/dashboards:/etc/grafana/dashboards:ro
    networks:
      - backend_network
    depends_on:
      - prometheus_auth

  node_exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - backend_network


volumes:
  postgres_data_auth:
  redis_data_auth:
  prometheus_data:
  grafana_data:

networks:
  backend_network:
    driver: bridge