apiVersion: 1

datasources:
  - name: Prometheus-Auth
    type: prometheus
    uid: prometheus-auth
    access: proxy
    url: http://prometheus_auth:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST